#+AUTHOR: Jared Arcilla
#+STARTUP: logdone
#+HUGO_SECTION: ./posts
#+HUGO_BASE_DIR: ../../
* Reviews :reviews:
* Reflections :@reflections:
** TODO Peter Larisey
:PROPERTIES:
:EXPORT_TITLE: Remembering Fr. Peter Larisey
:EXPORT_FILE_NAME: remembering_fr_peter.md
:END:

* Emacs :emacs:tech:

* Existentialism :philosophy:
* Blog :blog:
** DONE First Post
CLOSED: [2020-06-19 Fri 23:17]
:PROPERTIES:
:EXPORT_TITLE: First Post
:EXPORT_FILE_NAME: first_post.md
:END:
*** Why a blog?
Ever since I dove into emacs for the first time, I've been filling my laptop up with pages and pages of journals, notes and reviews.

A lot of my journalling is very private, consisting of intimate thoughts that I just needed to get down on paper. For a small subset of my writings, however, like reviews, how-to's, reflections, some of it I do want to share.

Also here I'm able to use $\LaTeX$ - something that I've always wanted on Twitter.

*** Who is this meant for?
A lot of my content won't be made for an audience in mind, but rather made for that rare moment when someone asks:

#+BEGIN_QUOTE
Why are you using Emacs?

What did you think about X movie or Y album?
#+END_QUOTE

Then I can dump a whole blog post in their DM's rather than retype my thoughts.

In the future, when I've gotten the hang of things, I do want to start posting about mental health and philosophy. In my darkest times, I scoured the internet trying to find someone who understood what I was going through. I hope I can be that person for someone else.
